### ISSUE TITLE
Output icon

### ISSUE THREAD

**Issue by dancuer92** [google/material-design-icons#420] opened 2016-06-20 16:03 UTC
Hola, estuve buscando un icono que fuera contrario al input que es una flecha que ingresa, y quisiera que fuera una flecha de salida.

![output](https://cloud.githubusercontent.com/assets/12980855/16201439/0226ea74-36d7-11e6-86b1-f618c345a78c.png)
![input](https://cloud.githubusercontent.com/assets/12980855/16201440/024eb95a-36d7-11e6-841a-7fee58765bdb.png)

**Comment by shyndman** [comment] 2016-07-14 13:04
Translated:
Hi, I'm looking for an icon that was contrary to the input that is an arrow that enters, and want it to be an arrow out.

**Comment by RoelN** [comment] 2021-02-23 15:16
Duplicate of https://github.com/google/material-design-icons/issues/160

**Closed by RoelN** 2021-02-23 15:16 UTC
Labels: icon request
