### ISSUE TITLE
push_pin is not more evailable

### ISSUE THREAD

**Issue by Kassan424kh** [google/material-design-icons#1310] opened 2022-05-11 09:25 UTC
after update the link of google icons in my site/project, the `push_pin` is not more evailable

![image](https://user-images.githubusercontent.com/46401401/167816788-8493b865-e41b-468e-a7a8-2da1d0fdb0f9.png)

**Comment by tphinney** [comment] 2022-05-11 20:13
This is in Material Symbols, not Material Icons, correct?
This is a duplicate of an issue covered in https://github.com/google/material-design-icons/issues/1304

That said, my apologies, I created the problem (through an unfortunate confluence of factors). I have fixed it in my far upstream font source, but I can’t tell you a date when that update will reach you. “Real Soon Now” is a good guess. Definitely not this week.

**Comment by Kassan424kh** [comment] 2022-05-11 20:35
Yes correct, this is in Material Symbols not in Icons.
Thank you.

**Comment by tphinney** [comment] 2022-05-11 20:42
OK, closing this as a duplicate. Watch the other issue for any update on release. But basically, whenever the next Material Symbols update comes, it should fix this.

**Comment by Kassan424kh** [comment] 2022-05-11 20:43
👌🏻

**Closed** 2022-05-11 20:43 UTC
Labels: duplicate
