### ISSUE TITLE
print_disabled icon looks exactly like print

### ISSUE THREAD

**Issue by acherniak** [google/material-design-icons#831] opened 2018-07-28 11:07 UTC
`<i class="material-icons">print_disabled</i>`  looks exactly like `<i class="material-icons">print</i>`

**Comment by eelcowen** [comment] 2018-07-31 08:27
This all has to do with issue Google not updating this Git repository.
Duplicate of #786

**Comment by RoelN** [comment] 2021-01-05 13:22
Looks like this has been addressed: https://github.com/google/material-design-icons/search?q=filename%3Aprint_disabled

If not, feel free to reopen this issue or create a new one with more information.

**Closed by RoelN** 2021-01-05 13:22 UTC
