### ISSUE TITLE
Website Errors?

### ISSUE THREAD

**Issue by DerekTBrown** [google/material-design-icons#662] opened 2017-08-05 09:09 UTC
I cannot load `https://material.io/icons/`.  I get the following error in Chrome:

```
webcomponents.js?v13:4855 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at addCssToDocument (webcomponents.js?v13:4855)
    at webcomponents.js?v13:4877
    at webcomponents.js?v13:4931
addCssToDocument @ webcomponents.js?v13:4855
(anonymous) @ webcomponents.js?v13:4877
(anonymous) @ webcomponents.js?v13:4931
webcomponents.js?v13:116 Uncaught Error: Assertion failed
    at assert (https://material.io/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:116:21)
    at assertIsNodeWrapper (https://material.io/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:1609:7)
    at GeneratedWrapper.insertBefore (https://material.io/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:1823:9)
    at GeneratedWrapper.appendChild (https://material.io/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:1820:21)
    at HTMLHeadElement.constructor.(anonymous function) [as appendChild] (https://material.io/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:353:28)
    at https://material.io/icons/webcomponents/third-party.js:10:332
    at https://material.io/icons/webcomponents/third-party.js:10:2672
assert @ webcomponents.js?v13:116
assertIsNodeWrapper @ webcomponents.js?v13:1609
insertBefore @ webcomponents.js?v13:1823
appendChild @ webcomponents.js?v13:1820
constructor.(anonymous function) @ webcomponents.js?v13:353
(anonymous) @ third-party.js:10
(anonymous) @ third-party.js:10
first-party.js:1 Uncaught ReferenceError: Polymer is not defined
    at first-party.js:1
(anonymous) @ first-party.js:1
deps-1.7.html:5600 Uncaught TypeError: Polymer17.DomModule.import is not a function
    at Object.cssBuildTypeForModule (deps-1.7.html:5600)
    at HTMLStyleElement._prepStyles (deps-1.7.html:6174)
    at HTMLStyleElement._registerFeatures (deps-1.7.html:6945)
    at HTMLStyleElement.registerCallback (deps-1.7.html:195)
    at desugar (deps-1.7.html:79)
    at window.Polymer17 (deps-1.7.html:63)
    at deps-1.7.html:6998
    at deps-1.7.html:7100
cssBuildTypeForModule @ deps-1.7.html:5600
_prepStyles @ deps-1.7.html:6174
_registerFeatures @ deps-1.7.html:6945
registerCallback @ deps-1.7.html:195
desugar @ deps-1.7.html:79
window.Polymer17 @ deps-1.7.html:63
(anonymous) @ deps-1.7.html:6998
(anonymous) @ deps-1.7.html:7100
deps-1.7.html:5600 Uncaught TypeError: Polymer17.DomModule.import is not a function
    at Object.cssBuildTypeForModule (deps-1.7.html:5600)
    at HTMLElement._prepStyles (deps-1.7.html:6174)
    at HTMLElement._registerFeatures (deps-1.7.html:6945)
    at HTMLElement.registerCallback (deps-1.7.html:195)
    at desugar (deps-1.7.html:79)
    at window.Polymer17 (deps-1.7.html:63)
    at material-io-nav-1.7.html:5
cssBuildTypeForModule @ deps-1.7.html:5600
_prepStyles @ deps-1.7.html:6174
_registerFeatures @ deps-1.7.html:6945
registerCallback @ deps-1.7.html:195
desugar @ deps-1.7.html:79
window.Polymer17 @ deps-1.7.html:63
(anonymous) @ material-io-nav-1.7.html:5
deps-1.7.html:5600 Uncaught TypeError: Polymer17.DomModule.import is not a function
    at Object.cssBuildTypeForModule (deps-1.7.html:5600)
    at HTMLElement._prepStyles (deps-1.7.html:6174)
    at HTMLElement._registerFeatures (deps-1.7.html:6945)
    at HTMLElement.registerCallback (deps-1.7.html:195)
    at desugar (deps-1.7.html:79)
    at window.Polymer17 (deps-1.7.html:63)
    at material-io-nav-1.7.html:502
cssBuildTypeForModule @ deps-1.7.html:5600
_prepStyles @ deps-1.7.html:6174
_registerFeatures @ deps-1.7.html:6945
registerCallback @ deps-1.7.html:195
desugar @ deps-1.7.html:79
window.Polymer17 @ deps-1.7.html:63
(anonymous) @ material-io-nav-1.7.html:502
webcomponents.js?v13:116 Uncaught Error: Assertion failed
    at assert (webcomponents.js?v13:116)
    at assertIsNodeWrapper (webcomponents.js?v13:1609)
    at GeneratedWrapper.insertBefore (webcomponents.js?v13:1823)
    at (index):51
    at (index):52
```

**Comment by shyndman** [comment] 2017-08-06 18:11
Duplicate of #658

**Closed** 2017-08-06 20:38 UTC
