### ISSUE TITLE
[Icon request] reddit, twitter

### ISSUE THREAD

**Issue by dotnetCarpenter** [google/material-design-icons#373] opened 2016-04-28 21:23 UTC
This is a great service but it's missing social icons, which pretty much is a requirement for all the sites I create.
Right now, twitter and reddit is missing before I can use the icon-set. I'll have to go to [IcoMoon](https://icomoon.io/) and wrap that in a component.

> re-posted from https://github.com/PolymerLabs/polyicon/issues/2

**Comment by frankbroniewski** [comment] 2016-05-03 20:06
I agree, it would be nice to have the typical social media icon set too.

**Comment by emanb29** [comment] 2016-06-23 16:20
+1, but duplicate of #350

**Comment by shyndman** [comment] 2016-07-14 15:11
Closing as dupe

**Closed by shyndman** 2016-07-14 15:11 UTC
