### ISSUE TITLE
Impossible to clone on Windows due to long file names

### ISSUE THREAD

**Issue by davideangeli** [google/material-design-icons#1076] opened 2020-09-09 06:40 UTC
It is impossible to clone this repository on Windows machines because of several files with filename to long

**Comment by maxloh** [comment] 2020-09-09 15:24
https://superuser.com/a/1225846/1172895

**Comment by davideangeli** [comment] 2020-09-10 07:48
> https://superuser.com/a/1225846/1172895

I've enabled this policy for long path names on my Windows 10 (2004 version) but it still doesn't work. I'm not able to clone this repository without errors.

**Comment by bryan-sullivan-ascendlearning-com** [comment] 2020-09-21 17:21
I am having the same issue as David. I've enabled Win32 long paths on Windows 10 and run gpupdate /force as well.

**Comment by AdrianTroy** [comment] 2020-10-09 12:18
I found this for you, I think it will help

https://superuser.com/questions/1519537/robocopy-command-to-copy-updated-files-and-long-path-names?r=SearchResults

**Comment by RoelN** [comment] 2021-01-05 11:31
@davideangeli Hoping that these suggestions solved the problem, I'm closing this issue. If the problem persists, feel free to reopen this issue or create a new one.

**Closed by RoelN** 2021-01-05 11:31 UTC

**Comment by davideangeli** [comment] 2021-01-07 15:22
Unfortunatly the problem is not solved. I suppose that the only solution could be to review the repository folder structure avoiding such log names. For now I have to download the zip file from the github repository.

**Comment by Fooughhy** [comment] 2021-08-13 12:49
This should definitely not be a closed issue. The issue still persists and, as @davideangeli said, none of the above "fixes" have helped. When I clone the repo, I only get the directories "android", "font" and "ios". So I'm unable to get any of the actual ".png" files which would be usable straight away.

The issue is also with simply cloning the repo, so any "copy" fixes are not relevant as I haven't actually gotten the files locally at all.
