### ISSUE TITLE
Install Problem with latest update

### ISSUE THREAD

**Issue by Klathmon** [google/material-design-icons#342] opened 2016-03-18 13:35 UTC
installing version 2.2.2 in NPM gives the error "npm ERR! cb() never called!" and halts all install progress.

Installing version 2.2.1 works fine.

This halts the entire `npm install` process for the whole package.json

I have tried and gotten the same results with both npm versions 3.7.3  and 3.8.3

**Comment by shyndman** [comment] 2016-03-19 19:58
Hey @Klathmon,

I'm taking a look now.

**Comment by shyndman** [comment] 2016-03-19 20:46
Hm, I can't figure this out. I've reported the problem to npm.

**Comment by Garbee** [comment] 2016-03-21 21:43
What version of NPM is being ran? Doing some searching it looks like using old versions may cause this error.

**Comment by shyndman** [comment] 2016-03-21 21:44
> I have tried and gotten the same results with both npm versions 3.7.3 and 3.8.3

**Comment by Garbee** [comment] 2016-03-21 21:47
Ah, interesting. (Sorry, missed that part.)

I'm running `3.7.3` and `^2.2.2` works perfect for me when installing. So, seems to be configuration-related then.

**Comment by Garbee** [comment] 2016-03-21 21:52
Ah wait, I had to remove my `node_modules` folder first, now it is reproducing on both `3.7.3` and `3.8.3`.

**Comment by shyndman** [comment] 2016-03-21 23:06
Ugh, too bad.

https://github.com/npm/npm/issues/11976 suggests this is happening for several projects. Let's hope it's resolved quickly.

**Comment by RoelN** [comment] 2021-02-12 11:02
Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Closed by RoelN** 2021-02-12 11:02 UTC
Labels: bug
