### ISSUE TITLE
Subset icon font

### ISSUE THREAD

**Issue by Angg4r4** [google/material-design-icons#1280] opened 2022-03-12 09:12 UTC
Subset icon font

_Originally posted by @Angg4r4 in https://github.com/google/material-design-icons/issues/1201#issuecomment-1065847494_

**Comment by tphinney** [comment] 2022-04-23 23:39
This seems to be a duplicate of #1201 
If you want to support an existing request, giving it a thumbs-up (or commenting on it if you have something specific to say) is the appropriate way to do that.

If you had some other request or suggestion, please clarify and we can reopen this issue.

**Closed by tphinney** 2022-04-23 23:39 UTC
Labels: duplicate
