### ISSUE TITLE
Not informed the code point of the icon: drag_indicator

### ISSUE THREAD

**Issue by samuelcust** [google/material-design-icons#841] opened 2018-08-09 22:34 UTC
There was no information in the list of [code points](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints) the icon drag_indicator.

**Comment by jestelle** [comment] 2018-09-17 18:00
Unfortunately we're quite behind on this project.
We expect to catch up on all of this - but it may take us a while before we're able to revisit it in full.
Sorry for the inconvenience.

**Comment by meoblast001** [comment] 2019-05-23 09:14
Is it possible this is a duplicate of #568?

**Comment by MurhafSousli** [comment] 2020-03-22 11:53
This is still an issue since 2 years!

**Comment by tphinney** [comment] 2022-05-04 05:49
I think this was eventually updated. Please let me know if it is still a problem? And if so at what location(s).

**Comment by tphinney** [comment] 2022-05-04 05:56
The original link is simply broken, but the latest codepoints files seem good.
https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints
generally these get updated at the same time as the fonts, nowadays.

**Closed by tphinney** 2022-05-04 05:56 UTC
Labels: bug
