### ISSUE TITLE
Request to add new male/female person icons

### ISSUE THREAD

**Issue by verengi** [google/material-design-icons#313] opened 2016-02-18 09:37 UTC
Hi,
it would be great if the icons could be extended with new male, female, child(e.g. male/female) and children icon.
Cheers

**Comment by BMartinos** [comment] 2016-03-23 08:45
+1

**Comment by marfago** [comment] 2016-05-20 21:46
+1

**Comment by martineckardt** [comment] 2016-06-18 10:18
I'm missing the common mirror (female) and circle+speer (male)

+1

**Comment by emiliofonseca** [comment] 2017-03-22 23:33
+1

**Comment by EricMartori** [comment] 2017-07-28 11:36
+1

**Comment by jagomf** [comment] 2017-09-06 08:25
+1. Anyway this is a duplicate of #242

**Comment by RoelN** [comment] 2021-02-23 14:00
#242 was for female and male gender (sex) icons, which have been added. Keeping this issue open for the request for male/female person icons.

**Comment by jalpadoshi** [comment] 2022-02-01 06:31
Icon available at: https://fonts.google.com/icons

**Comment by jalpadoshi** [comment] 2022-02-01 06:31
Icon available at: https://fonts.google.com/icons

**Closed** 2022-02-01 07:16 UTC
Labels: icon request
