### ISSUE TITLE
'Text decrease' has a wrong filled variant

### ISSUE THREAD

**Issue by Craftplacer** [google/material-design-icons#1582] opened 2023-09-25 19:23 UTC
| increase | decrease (no fill) | decrease (with fill) |
| - | - | - |
| ![image](https://github.com/google/material-design-icons/assets/22963120/7833be15-83cd-4cc8-93f0-1da133d66b64) | ![image](https://github.com/google/material-design-icons/assets/22963120/cd9ceb59-ae14-4cf8-b433-d4f6c3fbbb3a) | ![image](https://github.com/google/material-design-icons/assets/22963120/f3ea8d90-a498-4279-819e-b6d40811464d) |

**Comment by tphinney** [comment] 2023-09-27 02:45
Ouch. Yes, that looks like an error in mapping the startpoint between masters in the variable font.
What is funny is, that icon doesn’t even have a Fill effect.

(checks source) Yes, that is the cause of the problem alright. The 20 px and 20 px Filled masters both have a different position for the Startpoint, two stops further along the contour. We can fix this pretty easily.

**Comment by tphinney** [comment] 2023-10-11 17:19
We fixed this the last build! I don’t know when that will be released externally. The loose files here in the repo may take longer to get updated than the live web font.

**Closed** 2023-10-12 20:20 UTC
Labels: bug

**Comment by tphinney** [comment] 2023-10-12 20:22
I should add, this sparked a fontwide review from my colleague Vassil Kateliev. As he suspected, there are more such cases (the same root problem) that he has since fixed in our font source, although have yet to build fonts afterwards.

So we really appreciate the feedback @Craftplacer !
