### ISSUE TITLE
OTS parsing error

### ISSUE THREAD

**Issue by vinz** [google/material-design-icons#1222] opened 2021-09-15 12:59 UTC
Fonts just are not decodable, maybe the file is just somehow corrupted...

Even the google demo is not working at https://fonts.google.com/icons?selected=Material+Icons
When you choose filled, all icons are becoming blank on some windows machines and the error details are in the console as follows:

```
Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v102/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
OTS parsing error: Unable to instantiate font face from font data.
```

Many users are affected, please help resolve it ASAP.

Thank you

**Comment by oneart-dev** [comment] 2021-09-15 14:02
+1 happened for our customers as well. Not all but some. Chrome Windows 7 confirmed

**Comment by BeFede** [comment] 2021-09-15 16:41
+1

**Comment by rsheeter** [comment] 2021-09-15 16:46
Thank you for reporting; passing on internally

**Comment by rsheeter** [comment] 2021-09-15 16:52
Reporting the exact browser and OS version would be helpful. As is traditional for software issues it works for me (93.0.4577.63 (Official Build) (x86_64), macOS 11.6).

**Comment by BeFede** [comment] 2021-09-15 16:55
OS: Windows 7
Browser: Google Chrome 93.0.4577.82 (Build oficial) (32 bits)

**Comment by BeFede** [comment] 2021-09-15 17:42
On Windows 7 professional works well

**Comment by garretrieger** [comment] 2021-09-15 18:24
Rollback just completed for the fonts. Can you confirm if the OTS errors have gone away (be sure to reload with cache disabled or clear your cache)

**Comment by BeFede** [comment] 2021-09-15 18:43
Yes, now it works!

**Comment by garretrieger** [comment] 2021-09-15 22:22
I'm trying to narrow down the change that introduced the OTS failure and we haven't been able to reproduce on our test machines yet. Would you be able to try out this test page: https://cdpn.io/garretrieger/debug/WNOXKRE/nqMwvzxbxDyk and let me know if the house icon fails to render for either of the A or B line?

**Comment by BeFede** [comment] 2021-09-15 23:24
Oh sorry but i dont have a premium account. I can't see the page :(

**Comment by garretrieger** [comment] 2021-09-15 23:53
Oh sorry, try this one instead: https://codepen.io/garretrieger/pen/WNOXKRE

**Comment by BeFede** [comment] 2021-09-16 13:04
![photo_2021-09-16_10-04-25](https://user-images.githubusercontent.com/14844322/133617182-719c2fee-87e6-4f51-9e06-7d2492979891.jpg)

**Comment by garretrieger** [comment] 2021-09-16 15:46
Thanks!

**Comment by tphinney** [comment] 2022-04-24 04:40
@garretrieger can we close this now?

**Comment by garretrieger** [comment] 2022-04-27 18:15
Yes, we tracked down the issue to a problem with Win7's font parsing being dependent on the internal ordering of subtables and I fixed our font subsetter to avoid the problematic ordering: https://github.com/harfbuzz/harfbuzz/commit/49c9392412ccf31cf948310acda057b96eb6afc6

**Closed** 2022-04-27 19:24 UTC
Labels: bug
