### ISSUE TITLE
File types

### ISSUE THREAD

**Issue by brentcas** [google/material-design-icons#375] opened 2016-05-02 16:00 UTC
Would be good to have icons for popular file types such as .jpg, .png, .gif, .doc, .pdf, etc.

**Comment by VTG38** [comment] 2016-05-02 19:03
I agree.

**Comment by phidias51** [comment] 2016-07-02 18:03
I put in a similar request last year, but there doesn't seem to be much progress on the issue: https://github.com/google/material-design-icons/issues/226

**Comment by shyndman** [comment] 2016-07-14 15:10
Dupe of #226

**Closed by shyndman** 2016-07-14 15:10 UTC
