### ISSUE TITLE
Request: add "reminder" icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/material-design-icons#343] opened 2016-03-20 15:21 UTC
I suggest it to look like a finger with a knot on it.
I think it would be perfect for this case.

**Comment by Primajin** [comment] 2016-11-14 14:47
This is a duplicate of #229

**Comment by RavenHursT** [comment] 2018-02-28 21:34
And it's still not there...

**Comment by Primajin** [comment] 2018-03-01 06:39
For the time being you can use the unofficial version from here https://materialdesignicons.com/icon/reminder

**Comment by Primajin** [comment] 2018-03-01 09:29
The <span style="color:orange">orange</span> icons are from the community. And the other ones are somehow extracted - so they are the *original* icons but not *officially* released that way 😉

**Comment by AndroidDeveloperLB** [comment] 2018-03-01 09:40
@Primajin I don't understand, but as long as we are free to use it as we wish, I don't care how you call it : Alpha, Beta, preview, unofficial, WIP, ...

**Comment by Primajin** [comment] 2018-03-01 09:44
From https://github.com/Templarian/MaterialDesign#license

## License

Templates - [WTFPL](http://www.wtfpl.net/)

Community Icons - [SIL Open Font License 1.1](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web)

Google Material Design Icons - [Apache License 2.0](https://github.com/google/material-design-icons/blob/master/LICENSE)

... so go ahead 😄

**Comment by AndroidDeveloperLB** [comment] 2018-03-01 09:50
What "Templates" ? 
And what's "SIL"? It's for fonts only? If so, how is it related to the icons here?

**Comment by AndroidDeveloperLB** [comment] 2018-03-01 09:51
And how Apache can work on icons? I though it requires to let the comments of it stay in code, but here it's not code...

**Comment by Primajin** [comment] 2018-03-01 09:59
Sorry I'm not a legal expert here. From my understanding it's free to use - and I do so - but I can't give any guarantee on that.

**Comment by AndroidDeveloperLB** [comment] 2018-03-01 10:11
@Primajin But what are "Templates" ? 
Where did you get this information?

**Comment by Primajin** [comment] 2018-03-01 10:32
@AndroidDeveloperLB Umm from the Link right at the beginning of my message 🤔

**Comment by AndroidDeveloperLB** [comment] 2018-03-01 11:22
@Primajin Oops sorry. The link was above a title so for some reason I ignored it.

**Comment by RavenHursT** [comment] 2018-03-01 17:05
Thank you for this @Primajin! This is awesome.  Now to just do the work to get it into my React project :-/

Wonder if someone's already done a wrapper for it...?

**Comment by RavenHursT** [comment] 2018-03-01 17:06
#woopwoop! https://github.com/levrik/mdi-react

**Comment by RoelN** [comment] 2021-02-12 11:03
Closing this in favor of https://github.com/google/material-design-icons/issues/229

**Closed by RoelN** 2021-02-12 11:03 UTC
