### ISSUE TITLE
ic_menu_white is in Bitmap mode

### ISSUE THREAD

**Issue by hidrodixtion** [google/material-design-icons#154] opened 2015-06-19 09:53 UTC
ic_menu_white has black background and turned out it is saved in Bitmap mode, not in Grayscale mode. Thus it doesn't have transparent background.

![screen shot 2015-06-19 at 4 52 21 pm](https://cloud.githubusercontent.com/assets/52334/8251067/9b06d268-16a3-11e5-800e-49bec2d6d35e.png)

**Comment by shyndman** [comment] 2015-06-22 14:51
Can you point to a specific file in the repo so I can take a look?

**Comment by hidrodixtion** [comment] 2015-06-22 15:04
Inside [navigation](https://github.com/google/material-design-icons/tree/master/navigation) folder, all file with name **ic_menu_white_xxdp.png**. It shows perfectly when viewed using browser, but when I import it for Android Project, there's black background and when I open it using Photoshop the image mode is in Bitmap, not Grayscale like the others.

I just found out today that there are other files like that :
* ic_fullscreen_white_xxdp.png
* ic_fullscreen_exit_white_xxdp.png

**Comment by shyndman** [comment] 2015-06-22 15:41
Interesting. I'll take a look.

**Comment by PetrDana** [comment] 2015-06-30 09:13
Not only this icons, but also i.e. x(x)(x)hdpi ic_add_white_24(36)(48)dp.png has only 1 bit color depth (18dp version is ok).

**Comment by jestelle** [comment] 2015-07-08 00:50
This looks related to issue #137 

Can you let us know where you're finding these icons incorrectly rendering?  Is it only in Android Studio?  Or do you see it in your apps too?

Note this bug against Android Studio: https://code.google.com/p/android/issues/detail?id=178071

**Comment by hidrodixtion** [comment] 2015-07-08 03:27
I see it in my apps too not only in Android Studio.

**Comment by shyndman** [comment] 2015-07-08 14:04
We'll take a look. Thanks @hidrodixtion.

**Comment by shyndman** [comment] 2015-07-09 00:53
@hidrodixtion, we haven't been able to reproduce. Would you mind sending us more information about how you're using the icon?

**Comment by hidrodixtion** [comment] 2015-07-15 02:47
I'm using [android-drawable-importer-intellij-plugin](https://github.com/winterDroid/android-drawable-importer-intellij-plugin)

This is how it looks like in android studio: (ic_action_stop)
![screen shot 2015-07-15 at 9 41 21 am](https://cloud.githubusercontent.com/assets/52334/8689781/6de3c4d4-2ad6-11e5-8b39-23d06b6e32c7.png)

This is how it looks like in my app: (on floating action button)
![screen shot 2015-07-15 at 9 44 24 am](https://cloud.githubusercontent.com/assets/52334/8689783/7acf5b5e-2ad6-11e5-9868-a7b7fb875b96.png)

Compared to when I use ic_action_play:
![screen shot 2015-07-15 at 9 45 05 am](https://cloud.githubusercontent.com/assets/52334/8689786/7f3eddea-2ad6-11e5-8f8c-f12e0d1632cb.png)

**Comment by jestelle** [comment] 2015-07-20 16:57
@hidrodixtion You might try copying the files into your project directly, and _not_ using that importer tool.
I'm guessing that tool may be introducing the problem.

**Comment by RoelN** [comment] 2021-02-23 15:14
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

**Closed by RoelN** 2021-02-23 15:14 UTC
Labels: bug
