### ISSUE TITLE
Bump NPM library version number

### ISSUE THREAD

**Issue by esteladiaz** [google/material-design-icons#1065] opened 2020-08-28 18:08 UTC
Hello,

I'd like to use this library and have it installed into our project through NPM, but that package has not been updated in 4 years. Can the version number there be bumped to 4.0.0 please?

Thank you,

**Comment by macCesar** [comment] 2020-09-03 00:29
I just install it like this:

`npm install material-design-icons`

And get:

`+ material-design-icons@3.0.1 `

**So, please, can you update it to the latest version ??**

Thanks!!!

**Comment by rsheeter** [comment] 2020-09-03 04:00
Duplicate of #1050

**Closed by rsheeter** 2020-09-03 04:00 UTC
