### ISSUE TITLE
ic_stop_white_*dp.png background is black, not transparent

### ISSUE THREAD

**Issue by liquiddandruff** [google/material-design-icons#137] opened 2015-06-07 02:18 UTC
https://storage.googleapis.com/material-icons/external-assets/v1/icons/zip/ic_stop_white_48dp.zip

In Android Studio's preview window & in-app, the white stop icon's background is not like the others--there's no transparency and it's just black. The zips for each dp would need to be regenerated.

Eg
![image](https://cloud.githubusercontent.com/assets/2075654/8022360/a7cc87c2-0c80-11e5-8fb9-03beadf3eec5.png)
Compared to something like this
![image](https://cloud.githubusercontent.com/assets/2075654/8022361/c142f83a-0c80-11e5-9a32-ab2502c59430.png)

**Comment by shyndman** [comment] 2015-06-09 17:50
To be clear, are you taking the icons from this repo and importing them into Android Studio?

**Comment by liquiddandruff** [comment] 2015-06-10 03:00
It was from the png download link option on the [live site](https://www.google.com/design/icons/#ic_stop), not from the repo. I haven't checked yet if this problem's present with the resources in the repo.

**Comment by jestelle** [comment] 2015-06-24 17:27
Thanks for finding this Steven.  It looks like this is an Android Studio bug.
Feel free to use the asset, it will render correctly (with transparency) in your Android app, it just won't look correct in Android Studio.

We'll talk to the Android Studio team and get to the bottom of it.

**Comment by liquiddandruff** [comment] 2015-06-25 04:02
That's what I thought too but it wasn't just in Android Studio's preview window, it was also black and lacked alpha in-app.

**Comment by jestelle** [comment] 2015-06-25 04:13
Are you sure?  Which version of Android are you running?
I'm looking at a test app right now on Android L that appears correct to me, but maybe older versions of Android have a bug too?

**Comment by liquiddandruff** [comment] 2015-06-25 04:58
It happens on the android L emulator and my nexus 5 (5.1). It just appears to be an asset issue as other resources are fine. Again this is with the png link from the main site https://storage.googleapis.com/material-icons/external-assets/v1/icons/zip/ic_stop_white_48dp.zip not from repo.

**Comment by jestelle** [comment] 2015-07-08 00:50
I haven't been able to reproduce the problem in an emulator, or on device, but still looking into it.

Also, filed this bug against Android Studio:
https://code.google.com/p/android/issues/detail?id=178071

**Comment by Ron-Cai** [comment] 2015-07-12 04:41
I had the same problem with ic_menu_white_36dp for all sizes except hdpi. It seems like an android studio bug and if you just drag the files into the correct destination folders outside of Android Studio, the icon would be fine in the device, but still has the black background shown in Android Studio.

**Comment by cnevinc** [comment] 2016-05-05 16:14
ic_add_white_24dp.png also got this issue

**Comment by AbhinavDAIICT** [comment] 2016-07-03 04:04
@rotemge , @cnevinc : I'm using **ic_add_white_48dp.png** in **Android Studio 2.1.2**. While it shows a black background square in design preview, it is displayed correctly in the device.

**Comment by bl9009** [comment] 2016-07-12 09:00
same for ic_flight_takeoff_black_24px.svg and ic_flight_land_black_24px.svg
using them with QtQuick 2.3 and QtCreator 3.5.1
black background in preview and execution. using couple of icons of same size and format, which are all displayed as expected.

**Comment by everlutions** [comment] 2016-08-30 11:09
Same for ic_add_white_48dp downloaded through https://design.google.com/icons/. In the finder it shows transparency but in the android tools it has a black background. 

In app it has normal transparancy

**Comment by ofavre** [comment] 2017-05-31 07:55
I found the with icons that have either full opacity or full transparency pixels. For a given icon, it can depend on the actual size as scaling is involved.

Dolphin, Gwenview and Okular display those icons with an opaque black background.
ImageMagick (using the command display), Gimp and Chrome display them properly.

The PNGs are probably not bad per se, but I think they have been written in a not optimally compatible manner. Saving them from Gimp or running pngcrush on them fixes the issue, but adds an extra few bytes (not a big deal IMHO).

**Comment by MiralDesai** [comment] 2017-06-08 11:02
Weirdly I just came across this issue when converting my pngs to WebP. It was fine in PNG, now when I redownload the image (https://material.io/icons/#ic_add) it has a black background so a bit stuck.

Android Studio tells me they have a 1-bit colour profile which might be the issue.

**Comment by tigran-babajanyan** [comment] 2018-11-28 11:21
You can fix issue this way
open generated .xml file and change path android:fillColor from "#000000" to  "#00000000"

**Comment by RoelN** [comment] 2021-02-23 15:07
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

**Closed by RoelN** 2021-02-23 15:07 UTC
Labels: bug

**Comment by novartis-nk** [comment] 2023-06-06 16:25
thank you so much for reporting this!
I was struggling so much to see why I can't get it to be transparent on emulator

**Comment by Carmenlopezq** [comment] 2023-06-11 19:35
[Uploading 2020-07-20-exporte_genero.xlsx…]()

**Comment by Carmenlopezq** [comment] 2023-06-11 19:36
Duplicate of #[Gmail](jazminlopez2330
<details><summary>Details</summary>
<p>

> 

> @jazminlopez2330

</p>
</details> @gmail.com)
