### ISSUE TITLE
Toggle icons appear to be missing

### ISSUE THREAD

**Issue by jamesdalel** [google/material-design-icons#832] opened 2018-07-28 15:44 UTC
I have have been using material Icons for a while now and they are great!

However I need to use the toggle_off and toggle_on. These don't seem to work when implemented. I have updated the npm package to make sure that everything is up to date but I just get a blank space.

This will work
` <i className="material-icons">
      settings
  </i>`

This won't work
` <i className="material-icons">
      toggle_off
  </i>`

The icons exist in the docs https://material.io/tools/icons/?search=togg&icon=toggle_off&style=baseline

Any ideas?

Thanks, James

**Comment by eelcowen** [comment] 2018-07-31 08:26
This all has to do with issue Google not updating this Git repository.
Duplicate of #786

**Comment by jossef** [comment] 2018-10-27 19:13
@jamesdalel 

This project is on low maintenance and out of date for a while.

The lack of updates + development support issues also bothered me. I've forked this repo, added support for scss, removed irrelevant files and updated the fonts with the latest straight from Google's CDN.

### Check it out: [material-design-icons-iconfont](https://github.com/jossef/material-design-icons-iconfont)

![image](https://user-images.githubusercontent.com/1287098/47608007-44a8d200-da30-11e8-8750-694fb2fb26e4.png)



![image](https://user-images.githubusercontent.com/1287098/47608383-65bff180-da35-11e8-9faa-98d36e3a2b04.png)

![image](https://user-images.githubusercontent.com/1287098/47608379-5e004d00-da35-11e8-8af4-8c0ce86cb88c.png)

**Comment by RoelN** [comment] 2021-01-05 14:38
Closing this issue in favor of https://github.com/google/material-design-icons/issues/1085 which would address this!

**Closed by RoelN** 2021-01-05 14:38 UTC
