### ISSUE TITLE
Spelling error flourescent should be fluorescent

### ISSUE THREAD

**Issue by aardgoose** [google/material-design-icons#1208] opened 2021-08-12 14:19 UTC
The icon  https://fonts.google.com/icons?selected=Material+Icons&icon.query=flou&icon.category=device name is misspelled.

Should be fluorescent.

**Comment by tphinney** [comment] 2022-04-24 04:56
Yes, a sadly known issue. It was a typo when the icon was first created, but due to compatibility concerns, we can’t change it, as far as I know. I brought up the issue internally myself, when I started working on the variable font version of the icons.

In the font we can fairly easily accommodate multiple names in our ligature code—so we have set it up that you can actually type the name either way and still get the right glyph!

Also: duplicate of #1299 and #1211

**Closed by tphinney** 2022-04-24 04:56 UTC
Labels: duplicate

**Comment by tphinney** [comment] 2022-05-02 15:32
NOTE: Although we can’t get rid of the “bad” name for compatibility reasons, I have opened issue #1305 to ALSO support the icon under the corrected name, in the standalone graphic icons (both Material Symbols and Material Icons), and the Material Icons font. (Already supported in Material Symbols)

For anybody this matters to, you should consider commenting on or upvoting (thumbs-up) that issue!
