### ISSUE TITLE
Icon Request: Trophy Icon

### ISSUE THREAD

**Issue by edwinj84** [google/material-design-icons#403] opened 2016-05-27 14:17 UTC
An icon for trophies with material design has many app uses in apps that have challenges and achievements.

**Comment by viento2685** [comment] 2016-05-29 14:00
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  ???




On Friday, May 27, 2016, 7:18 AM, Edwin Jose <notifications@github.com> wrote:


An icon for trophies with material design has many app uses in apps that have challenges and achievements.

**Comment by jestelle** [comment] 2016-05-31 23:24
We encourage folks to use the "Add reaction" to add a thumbs up and vote up icon requests.
Popular requests we will try to accommodate, but our turn around on new icon requests is likely going to be fairly slow.

**Comment by dmacfarlane** [comment] 2016-06-16 20:01
Duplicate of #136

**Comment by joseedwin84** [comment] 2016-06-16 21:21
@dmacfarlane sorry, did not know. That Request was made a year ago.

**Comment by scheMeZa** [comment] 2018-06-24 09:02
2019? :D

**Comment by tomislavhofman** [comment] 2020-10-16 06:56
2021? :D

**Comment by jeffnear** [comment] 2020-10-25 15:51
2030?

**Comment by RoelN** [comment] 2021-02-12 09:15
3000?!?!?

There seems to be a trophy issue in the current set! \o/

<img width="657" alt="image" src="https://user-images.githubusercontent.com/4570664/107749274-97e6e180-6d1a-11eb-8173-6e27e5aa93f9.png">

(Also search "badge" for a... well, badge)

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Closed by RoelN** 2021-02-12 09:15 UTC
Labels: icon request
