### ISSUE TITLE
Icon Request: book

### ISSUE THREAD

**Issue by leejimin1006** [google/material-design-icons#382] opened 2016-05-06 13:57 UTC
![book](https://cloud.githubusercontent.com/assets/18396420/15075124/b75838fc-13dd-11e6-86db-e0fa556ceaf1.PNG)

This is Safari browser icon.

I wish this icon.

**Comment by shyndman** [comment] 2016-07-14 15:06
Dupe of #346

**Closed by shyndman** 2016-07-14 15:06 UTC
