### ISSUE TITLE
Icon 'table_chart' is wrong when i use in my site

### ISSUE THREAD

**Issue by caetanosasia** [google/material-design-icons#825] opened 2018-07-18 19:25 UTC
When i use this:
![wrong_icon](https://user-images.githubusercontent.com/32081312/42902910-8ae46bb4-8aa6-11e8-8157-7a5634d04ca5.png)
this appears:
![wrong_icon_2](https://user-images.githubusercontent.com/32081312/42903040-e99133ae-8aa6-11e8-810b-ae23ccb7774e.png)

**Comment by eelcowen** [comment] 2018-07-24 09:36
Duplicate of #786

**Comment by RoelN** [comment] 2021-02-03 14:48
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

If you use the font from the repo, or served from Google Fonts, this should be solved.

**Closed by RoelN** 2021-02-03 14:48 UTC
