### ISSUE TITLE
Icons page is offline

### ISSUE THREAD

**Issue by emergingdzns** [google/material-design-icons#660] opened 2017-08-04 00:53 UTC
The material icons page (https://material.io/icons/) is blank. It appears that the materials.io domain may have been hijacked or something.

**Comment by Whisperer** [comment] 2017-08-04 09:13
Maybe you're experiencing the same problem as: https://github.com/google/material-design-icons/issues/658 ?

For me it's working fine in any browser without the LastPass extension installed.

**Comment by deepu105** [comment] 2017-08-04 13:38
It doesnt work on chrome latest

**Comment by deepu105** [comment] 2017-08-04 13:39
stack trace on browser
```
webcomponents.js?v13:217 [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.
getDescriptor @ webcomponents.js?v13:217
installProperty @ webcomponents.js?v13:236
registerInstanceProperties @ webcomponents.js?v13:182
registerInternal @ webcomponents.js?v13:272
register @ webcomponents.js?v13:263
(anonymous) @ webcomponents.js?v13:4368
(anonymous) @ webcomponents.js?v13:4370
webcomponents.js?v13:4855 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at addCssToDocument (webcomponents.js?v13:4855)
    at webcomponents.js?v13:4877
    at webcomponents.js?v13:4931
addCssToDocument @ webcomponents.js?v13:4855
(anonymous) @ webcomponents.js?v13:4877
(anonymous) @ webcomponents.js?v13:4931
webcomponents.js?v13:116 Uncaught Error: Assertion failed
    at assert (https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:116:21)
    at assertIsNodeWrapper (https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:1609:7)
    at GeneratedWrapper.insertBefore (https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:1823:9)
    at GeneratedWrapper.appendChild (https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:1820:21)
    at HTMLHeadElement.constructor.(anonymous function) [as appendChild] (https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/bower_components/webcomponentsjs/webcomponents.js?v13:353:28)
    at https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/third-party.js:10:332
    at https://20170801t144119-dot-material-io.appspot.com/icons/webcomponents/third-party.js:10:2672
assert @ webcomponents.js?v13:116
assertIsNodeWrapper @ webcomponents.js?v13:1609
insertBefore @ webcomponents.js?v13:1823
appendChild @ webcomponents.js?v13:1820
constructor.(anonymous function) @ webcomponents.js?v13:353
(anonymous) @ third-party.js:10
(anonymous) @ third-party.js:10
first-party.js:1 Uncaught ReferenceError: Polymer is not defined
    at first-party.js:1
(anonymous) @ first-party.js:1
deps-1.7.html:5600 Uncaught TypeError: Polymer17.DomModule.import is not a function
    at Object.cssBuildTypeForModule (deps-1.7.html:5600)
    at HTMLStyleElement._prepStyles (deps-1.7.html:6174)
    at HTMLStyleElement._registerFeatures (deps-1.7.html:6945)
    at HTMLStyleElement.registerCallback (deps-1.7.html:195)
    at desugar (deps-1.7.html:79)
    at window.Polymer17 (deps-1.7.html:63)
    at deps-1.7.html:6998
    at deps-1.7.html:7100
cssBuildTypeForModule @ deps-1.7.html:5600
_prepStyles @ deps-1.7.html:6174
_registerFeatures @ deps-1.7.html:6945
registerCallback @ deps-1.7.html:195
desugar @ deps-1.7.html:79
window.Polymer17 @ deps-1.7.html:63
(anonymous) @ deps-1.7.html:6998
(anonymous) @ deps-1.7.html:7100
deps-1.7.html:5600 Uncaught TypeError: Polymer17.DomModule.import is not a function
    at Object.cssBuildTypeForModule (deps-1.7.html:5600)
    at HTMLElement._prepStyles (deps-1.7.html:6174)
    at HTMLElement._registerFeatures (deps-1.7.html:6945)
    at HTMLElement.registerCallback (deps-1.7.html:195)
    at desugar (deps-1.7.html:79)
    at window.Polymer17 (deps-1.7.html:63)
    at material-io-nav-1.7.html:5
cssBuildTypeForModule @ deps-1.7.html:5600
_prepStyles @ deps-1.7.html:6174
_registerFeatures @ deps-1.7.html:6945
registerCallback @ deps-1.7.html:195
desugar @ deps-1.7.html:79
window.Polymer17 @ deps-1.7.html:63
(anonymous) @ material-io-nav-1.7.html:5
deps-1.7.html:5600 Uncaught TypeError: Polymer17.DomModule.import is not a function
    at Object.cssBuildTypeForModule (deps-1.7.html:5600)
    at HTMLElement._prepStyles (deps-1.7.html:6174)
    at HTMLElement._registerFeatures (deps-1.7.html:6945)
    at HTMLElement.registerCallback (deps-1.7.html:195)
    at desugar (deps-1.7.html:79)
    at window.Polymer17 (deps-1.7.html:63)
    at material-io-nav-1.7.html:502
cssBuildTypeForModule @ deps-1.7.html:5600
_prepStyles @ deps-1.7.html:6174
_registerFeatures @ deps-1.7.html:6945
registerCallback @ deps-1.7.html:195
desugar @ deps-1.7.html:79
window.Polymer17 @ deps-1.7.html:63
(anonymous) @ material-io-nav-1.7.html:502
webcomponents.js?v13:116 Uncaught Error: Assertion failed
    at assert (webcomponents.js?v13:116)
    at assertIsNodeWrapper (webcomponents.js?v13:1609)
    at GeneratedWrapper.insertBefore (webcomponents.js?v13:1823)
    at (index):51
    at (index):52
```

**Comment by emergingdzns** [comment] 2017-08-04 13:48
Oh the irony...

**Comment by shyndman** [comment] 2017-08-05 00:34
This happens with the LastPass extension installed. I have a fix ready to go, but we're not going to be able to push until Monday.

Also, this is a dupe of #658.

**Closed** 2017-08-05 00:34 UTC
