### ISSUE TITLE
Icon Request: Trophy

### ISSUE THREAD

**Issue by endigo9740** [google/material-design-icons#784] opened 2018-05-18 03:14 UTC
For tournaments and other competitive game purposes. Potential variations:

- Default
- Featured: includes flag or star
- Won / Lost
- Status: Active / Completed

**Comment by dmacfarlane** [comment] 2018-06-08 21:56
Duplicate of #136

**Comment by jalpadoshi** [comment] 2022-01-31 23:34
Icon now available on: https://fonts.google.com/icons

**Closed by jalpadoshi** 2022-01-31 23:34 UTC
Labels: icon request
