### ISSUE TITLE
self host the iconfont, "Failed to decode downloaded font"

### ISSUE THREAD

**Issue by Tusiji** [google/material-design-icons#228] opened 2015-10-29 06:03 UTC
I'm try to self host the iconfont(http://google.github.io/material-design-icons/) , but its not work. The chrome console shows that:
```
Failed to decode downloaded font: file:///Users/Pan/Documents/Dev/MDL/Hiar/font/MaterialIcons-Regular.woff2
index.html:1 OTS parsing error: invalid version tag
index.html:1 Failed to decode downloaded font: file:///Users/Pan/Documents/Dev/MDL/Hiar/font/MaterialIcons-Regular.woff
index.html:1 OTS parsing error: invalid version tag
index.html:1 Failed to decode downloaded font: file:///Users/Pan/Documents/Dev/MDL/Hiar/font/MaterialIcons-Regular.ttf
index.html:1 OTS parsing error: invalid version tag
```

**Comment by shyndman** [comment] 2015-11-06 20:30
Duplicate of #205

**Closed by shyndman** 2015-11-06 20:30 UTC
Labels: bug
