### ISSUE TITLE
Baseline not correct for outlined, round and sharp

### ISSUE THREAD

**Issue by 4BRobby** [google/material-design-icons#922] opened 2019-04-11 12:46 UTC
Hey guys,
Unfortunately if you check and compare, the baseline of ex. outlined icons is completely off.

As seen below the mentioned icon types are set about 50% higher:
![image](https://user-images.githubusercontent.com/22675949/55958222-6e655680-5c68-11e9-8425-3d248f25dfbf.png)

Any chance this gets solved?

Thank you

**Comment by timc986** [comment] 2019-04-12 16:09
Glad that you mentioned it. 

Today I opened my old projects tried to play around, found out all the outlined, round, sharp icons are vertically off. Thought I messed up something in the past and didn't notice. Tried to change some css and didn't work. Changed those icons to inlined or two tone and those are fine and are not affected by this issue. 

As op mentioned it would be nice if this can be fixed, I guess it must be affecting a lot of users. (Or is this by design?)

![image](https://user-images.githubusercontent.com/32720097/56051070-747d3500-5d45-11e9-92ce-d03033129512.png)

**Comment by timc986** [comment] 2019-04-15 15:10
hey @4BRobby it seems fine now, may you please check? Thanks

**Comment by 4BRobby** [comment] 2019-04-15 20:13
Hello @timc986,

Baseline problem is gone! Great! At least solves the problems for the styles I want to use but the two-tone icons are now completely messed:
![image](https://user-images.githubusercontent.com/22675949/56162190-aef80380-5fcb-11e9-8f59-3bf94740e959.png)

Keep up the good work!

**Comment by timc986** [comment] 2019-04-18 17:06
Hey I didn't make change maybe someone else did.

Btw I just checked again on my win7 machine, the icons are still messed up but they seems fine on my other win10 machine, can anyone confirm?

**Comment by 4BRobby** [comment] 2019-04-18 20:31
> Hey I didn't make change maybe someone else did.
> 
> Btw I just checked again on my win7 machine, the icons are still messed up but they seems fine on my other win10 machine, can anyone confirm?

The messed up screenshot is on Windows 10. I have to check on Windows 7 again (first one I have posted with the baseline). Is this an issue on different OSes? Thought Chrome would display it the same way on Win7/Win10 (using Chrome latest stable)

**Comment by timc986** [comment] 2019-04-18 21:16
> > Hey I didn't make change maybe someone else did.
> > Btw I just checked again on my win7 machine, the icons are still messed up but they seems fine on my other win10 machine, can anyone confirm?
> 
> The messed up screenshot is on Windows 10. I have to check on Windows 7 again (first one I have posted with the baseline). Is this an issue on different OSes? Thought Chrome would display it the same way on Win7/Win10 (using Chrome latest stable)

On Windows 7, I have checked it on 2 different laptops and they both have the same issue.

So in summary, seems like there are 2 problems: 
On Windows 7, baseline is not correct for outlined, round and sharp icons, two tone is fine though.
On Windows 10, baseline is correct but the two tone is werid with the 360 icon over. [see another post](https://github.com/google/material-design-icons/issues/917)
Tried Chrome and Firefox on Win7 and Win10, behaviour is the same

Honestly I don't understand what is causing the problem, it worked totally fine until like last month.

**Comment by 4BRobby** [comment] 2019-04-18 21:35
Well I really thought this is fixed but had not in mind my working box is on Win7 and my home laptop is on Win10 and that this would make the difference.
I will recheck after easter on my Win7 box at work to confirm.

**Comment by timc986** [comment] 2019-04-18 21:45
> Well I really thought this is fixed but had not in mind my working box is on Win7 and my home laptop is on Win10 and that this would make the difference.
> I will recheck after easter on my Win7 box at work to confirm.

Maybe its not the OS then, thanks for your confirmation.

**Comment by timc986** [comment] 2019-04-18 22:14
Alright this is going to be my last update and after this I am going to forget about this mess and try to enjoy Easter.

So I test it on my another Windows 10 machine with the same compiled Angular code, baseline is correct for outlined, round and sharp icons. Different OS definitely causing something here.

**Comment by 4BRobby** [comment] 2019-04-24 16:03
Problem in opening post persists on Windows 7 / Chrome (latest)

**Comment by timc986** [comment] 2019-04-29 09:58
going to try those css change in the #206  later to see if it works, hopefully it won't break those working ones in Win10

**Comment by 4BRobby** [comment] 2019-04-30 09:37
One idea i had for fixing the baseline issue:
`.material-icons-outlined, .material-icons-round, .material-icons-sharp { line-height: 0; padding-top: 24px; }`
Adjust top-padding to any font-size you are using.

**Comment by timc986** [comment] 2019-06-07 18:26
After reading the comment on the other thread https://github.com/google/material-design-icons/issues/206#issuecomment-487554187 from @MicMicMon, I decided to combine mat-icon and iconify, works totally fine in win7 chrome firefox and win10 chrome firefox. This way you can use the angular material icons from iconify which works perfectly fine, and still keep the styling from the mat-icon. Thank you for everyone's help.

```
<mat-icon *ngIf="true">
      <span class="iconify" data-icon="ic:baseline-cloud" data-inline="false"></span>
 </mat-icon>

<mat-icon class="iconify" data-icon="ic:baseline-menu" data-inline="false"></mat-icon>

<script src="https://code.iconify.design/1/1.0.2/iconify.min.js"></script>
```

**Comment by 4BRobby** [comment] 2019-06-09 05:31
We have switched to SVG now as well but using an own IE/js-fallback with an own sprite graphics SVG library so far. But Iconify seems worth considering.

**Comment by brightest-dazes** [comment] 2019-06-09 14:39
I need someone to tell me how to fix this broken heart. I finally am of sober mind body Spirit and soul. I'm ready to begin the next chapter of the best of the rest of my life. 
As well as how to fix what is wrong with whatever program we're working on. Just so you know,by the way Spotify is number one in my book.

**Comment by RoelN** [comment] 2021-02-03 10:12
Hi all, thanks for sharing your debugging steps, and your solutions. The assets have been updated in the meantime, so this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

**Closed by RoelN** 2021-02-03 10:12 UTC
