### ISSUE TITLE
Unable to checkout with npm

### ISSUE THREAD

**Issue by gregbown** [google/material-design-icons#544] opened 2017-01-14 01:42 UTC
npm install material-design-icons --save-dev fails silently. The files seem to show up in the node_modules/staging but the installation never completes and no error logs are generated.

Windows 10 Professional, Node 6.9.1, npm 4.0.2

I filed a bug with npm as well but nothing came of it.

**Comment by thw0rted** [comment] 2018-06-23 13:22
Duplicate of #518

**Comment by RoelN** [comment] 2021-02-11 09:20
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information. Also, this looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

**Closed by RoelN** 2021-02-11 09:20 UTC
