### ISSUE TITLE
Accessing the metadata of the corresponding icon

### ISSUE THREAD

**Issue by arunkumar413** [google/material-design-icons#1332] opened 2022-06-23 15:28 UTC
Hello Team,

How to access the meta data of the corresponding svg icons located at https://github.com/google/material-design-icons/tree/master/src  ?

Thanks,
Arun

**Comment by tphinney** [comment] 2022-06-26 06:33
Can you be more specific? What metadata are you referring to?

**Comment by jonjhiggins** [comment] 2022-09-20 09:30
Hi, we're also looking for "tags" of associated words to describe Material Design Icons so we can build a UI component that can search the icons based on user keywords, exactly as the search in https://fonts.google.com/icons functions

Looks like there is a similar request here: https://github.com/google/material-design-icons/issues/1196

The in that issue the linked endpoint https://fonts.google.com/metadata/icons has exactly what we need in the "tags" property, but we're unsure if we're able to use this data as there isn't a license supplied with it?

Also it would be easier to work with if it was within the NPM package

Thanks
Jon

**Comment by david-mart** [comment] 2023-04-22 19:51
this is how I ended up getting svg paths for icons
```typescript
const getSvgPaths = async (icon: GFontsIcon): Promise<GFontsIcon> => {
  try {
    const { data } = await axios.get<string>(
      `https://raw.githubusercontent.com/google/material-design-icons/master/src/${icon.categories[0]}/${icon.name}/materialiconsoutlined/${icon.sizes_px[0]}px.svg`,
    );
    return { ...icon, paths: Array.from(data.match(/(?<= d=")([^"])*(?=")/gm)) };
  } catch (error) {
    return icon;
  }
};

const getGoogleIcons = async (q?: string, limit = 5) => {
  try {
    const { data } = await axios.get<string>('https://fonts.google.com/metadata/icons');
    const cleaned = JSON.parse(data.substring(5)) as GFontsResponse;
    const { icons } = cleaned;
    const res = icons.filter((icon) => icon.name.startsWith(q)).slice(0, limit);
    return Promise.all(res.map(getSvgPaths));
  } catch (error) {
    return [];
  }
};

```

<details>
  <summary>(Types)</summary>

  ```typescript
  export class GFontsResponse {
    host: string;
    asset_url_pattern: string;
    families: string[];
    icons: GFontsIcon[];
  }

  export class GFontsIcon {
    name: string;
    version: number;
    popularity: number;
    codepoint: number;
    unsupported_families: any[];
    categories: string[];
    tags: string[];
    sizes_px: number[];
    paths?: string[];
  }
  ```
</details>

**Comment by tphinney** [comment] 2023-04-24 01:26
Urm, interesting but… paths of the icons are not metadata!

Closing this as a duplicate of #1196 — but that doesn’t mean it is not to be considered.

**Closed by tphinney** 2023-04-24 01:26 UTC
