### ISSUE TITLE
Make NPM Package smaller

### ISSUE THREAD

**Issue by NCC1701M** [google/material-design-icons#579] opened 2017-03-15 08:05 UTC
Installing material-design-icons via npm tooks nearly 5 - 10 Minutes. This is much too long. The time needed for downloading the package is ok, but the extracting time is horrible.

This is way to much only for using material-icons.css and the included woff2 file.

**Comment by jestelle** [comment] 2017-03-17 23:15
Have you considered using the font as served from Google Fonts? 

http://google.github.io/material-design-icons/#icon-font-for-the-web

I'm going to consider this a duplicate of #133

**Closed by jestelle** 2017-03-17 23:15 UTC
Labels: duplicate, enhancement

**Comment by NCC1701M** [comment] 2017-03-18 08:12
I can't use it from Google Fonts because it should work as an offline app as well.

**Comment by shyndman** [comment] 2017-03-20 18:50
Hey @NCC1701M,

Maybe you could use a service worker? Take a look at this:
https://duske.me/improve-user-experience-with-service-worker-toolbox/

**Comment by NCC1701M** [comment] 2017-03-20 19:54
Thanks @shyndman 

I will give it a try but nonetheless should there be a smaller package without the sources
