### ISSUE TITLE
offline_bolt not available?

### ISSUE THREAD

**Issue by juristr** [google/material-design-icons#781] opened 2018-05-17 09:17 UTC
I just downloaded the latest version from master, but it seems like the `offline_bolt` is not available, also didn't find it in the [codepoints](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints)

![image](https://user-images.githubusercontent.com/542458/40168490-e2fea058-59c3-11e8-8a1b-80f90d265c70.png)

**Comment by meglio** [comment] 2018-11-14 02:33
I can confirm the issue is in the `3.0.1` release

**Comment by dussann** [comment] 2019-01-17 08:30
I can confirm too

**Comment by vlad-h** [comment] 2019-05-26 08:59
This issue still exists. Any solutions ?

**Comment by Klayemore** [comment] 2019-11-28 00:32
Not working for me also

**Comment by RoelN** [comment] 2021-02-09 09:10
This looks to be an issue with the outdated font of the 3.0.1 npm package. I'm closing this issue in favor of the central issue https://github.com/google/material-design-icons/issues/1129, where we keep track of updating it.

**Closed by RoelN** 2021-02-09 09:10 UTC
