### ISSUE TITLE
Icon Request: Double Chevron

### ISSUE THREAD

**Issue by shuegelm** [google/material-design-icons#969] opened 2019-12-06 09:23 UTC
I used the "newly" added feature to openAll and closeAll expansion-panels, but missed a nice fitting icon for this kind of "action". So our team decided to use "double chevron" as icon.

![image](https://user-images.githubusercontent.com/12783126/70311495-0fb1a600-1812-11ea-83f8-614f15a01655.png)

It is the same arrow which is pretty equal to the single expand/collapse action and using it twice maybe suggests that this is the function to collapse or expand all.

PS: There is also an icon request called "double chevron" but the implemented last and first page icon isnt quite exactly a "double" chevron. [See here](https://github.com/google/material-design-icons/issues/198)

**Comment by danieldanielecki** [comment] 2019-12-11 11:47
Duplicate of [#198](https://github.com/google/material-design-icons/issues/198).

**Comment by tjlittle** [comment] 2020-02-17 18:58
I don't think this is a duplicate - the items in #198 are for horizontal double-chevrons. This request is for vertical double-chevrons.

**Comment by danieldanielecki** [comment] 2020-02-27 14:02
@tjlittle you're right, my bad.

**Comment by jalpadoshi** [comment] 2022-01-31 23:32
Icon now available on: https://fonts.google.com/icons 

keyboard_double_arrow_down
keyboard_double_arrow_left
keyboard_double_arrow_right
keyboard_double_arrow_up

**Closed by jalpadoshi** 2022-01-31 23:32 UTC
Labels: icon request
