### ISSUE TITLE
Material Symbols `language` with weight `100`-`300` is deformed at `20dp` size

### ISSUE THREAD

**Issue by SunniMango** [google/material-design-icons#1528] opened 2023-06-12 08:41 UTC
### Description
The `language` Material Symbol with a weight of `100`-`300` is deformed at `20dp` size. This shows up for any selection of Grade, Fill, or Shape (rounded, outlined, sharp).

### Steps to Reproduce
- Go to [fonts.google.com/icons](https://fonts.google.com/icons).
- Ensure you are using the **Material Symbols icon** set.
- Search for **language**.
- Under **Customization**, change the weight parameter to any weight from `100` to `300` and put optical size to `20dp`.
- Language (`language`) icon becomes deformed.
<img width="134" alt="Screenshot 2023-06-12 at 10 39 50" src="https://github.com/google/material-design-icons/assets/136315196/fecd8f9b-6c2c-4d0a-a9b8-6012710a25f0">

**Comment by tphinney** [comment] 2023-06-24 19:49
Ah, I see the cause of the problem. The 20 pt and 20 pt Filled masters swap contours.
Easy fix, but not quite making the cutoff for the next release. I can fix it for the following release, however.

**Comment by tphinney** [comment] 2023-06-24 19:53
Checked in the source fix, will be in next build.

**Comment by jhuangfieldwire** [comment] 2023-07-18 19:09
@tphinney It seems there's a same problem for chevron_right under 20dp optical size with various weight. 
This screenshot is an example under 100 weight. 
<img width="255" alt="Screenshot 2023-07-18 at 11 37 25 AM" src="https://github.com/google/material-design-icons/assets/107725664/d97c2c97-dd45-4d24-abd2-83424b508769">

**Comment by tphinney** [comment] 2023-07-18 19:25
This is a different startpoint in the same contour across masters, rather than a confusion between contours. But it does have the same symptom of deformed interpolations!

**Comment by tphinney** [comment] 2023-07-19 02:27
Also tied in with a broken auto-layer in source, perhaps? Weird, seeing as /navigate_next is fine.

**Comment by Totati** [comment] 2023-08-10 08:39
I have found some more, as this issue is not closed I'm leaving it here 🙊:

- immunology at optical size 40px and 48px
- neurology at grade 200
- blur_on at weight 200 and 300
- edgesensor_* at weight 200 and 300
- media_bluetooth_on at weight 100, 200 and 300 at optical size 40py and 48px

By the way out of curiosity, were these icons generated?

**Comment by tphinney** [comment] 2023-08-11 06:17
I will look into these @Totati — thanks for the report!

**Comment by tphinney** [comment] 2023-08-13 02:17
I will just add that these sorts of interpolation or vector addition problems happen occasionally, typically when we have a mismatch between masters in either (1) which node on a contour is the startpoint, or (2) contour order when we also have two contours with the same number of points (and usually the same topology).

Anyway, these have all been fixed in our source font build, so should be in the next external updates, whenever those percolate through.

If you see issues in other glyphs, please open a separate bug rather than “piling on” this one.  :)

**Comment by tphinney** [comment] 2024-08-16 05:28
this was fixed last year

**Closed by tphinney** 2024-08-16 05:28 UTC
Labels: bug
