### ISSUE TITLE
Icon request: Disgendered

### ISSUE THREAD

**Issue by idc77** [google/material-design-icons#1271] opened 2022-02-22 18:45 UTC
In a dating (or partnership) app, I'm trying to give people the choice of their identity: [man, woman] is covered,
as well as their gender [male, female, transgender, disgendered].
Male, female and transgender are covered, but disgendered isn't.

While most relationships revolve around sex, some people are also asexual but still seeking a partner, some are also disgendered or have both genders but not completely evolved and are also seeking a partner.

I would hate for anyone to be or feel excluded.

**Comment by tphinney** [comment] 2022-04-24 02:52
Pardon me if I am unfamiliar with something important here… by disgender, do you mean the same thing as agender?
I don’t find any agreement on what a disgendered icon might be, but I think there is already a common sense of what a standard agender icon is:
https://www.google.com/search?q=agendered+icon

**Comment by tphinney** [comment] 2022-06-14 02:13
Oops, my own issue #1322 is a duplicate of this. Don’t know how I missed that.

I just wanted to say that an agender icon is coming! Should be available within the next few weeks, if I am correctly understanding the latest production workflow. Not this week, but soon.  :)

**Comment by tphinney** [comment] 2022-11-12 20:47
Agender was indeed added!

**Closed by tphinney** 2022-11-12 20:47 UTC
Labels: icon request
