### ISSUE TITLE
Icon request: Trophy

### ISSUE THREAD

**Issue by hassi2k7** [google/material-design-icons#169] opened 2015-07-12 09:37 UTC
I miss an icon to honor a user with a small trophy - that would be a good one for a new record in a sport app or a winner of a challenge or other rewards.

**Comment by dmacfarlane** [comment] 2016-04-05 19:56
Duplicate of #136

**Comment by RoelN** [comment] 2021-02-23 14:43
Duplicate of https://github.com/google/material-design-icons/issues/136 and https://github.com/google/material-design-icons/issues/403

**Closed by RoelN** 2021-02-23 14:43 UTC
Labels: icon request
