### ISSUE TITLE
Icon Request: Graph

### ISSUE THREAD

**Issue by itsryandrake** [google/material-design-icons#172] opened 2015-07-15 06:27 UTC
I'd like icons that demonstrate data/analytics.

Perhaps a pie chart, bar graph or some other icon?

**Comment by shyndman** [comment] 2015-07-19 22:41
Hey @itsryandrake,

We're working on it. No promises, but our next release should have at least a bar graph.

**Comment by shyndman** [comment] 2015-07-20 14:14
Dupe of #101

**Closed by shyndman** 2015-07-20 14:14 UTC
Labels: icon request
